In [117]:
import numpy as np
import re 

In [118]:

def read_arq():
    with open('input.txt', 'r') as arquivo:
        linhas = arquivo.readlines()
    seq_vert = linhas[0].strip()
    seq_horiz = linhas[1].strip()
    GAP = linhas[2].strip()
    mismatch = linhas[3].strip()
    match = linhas[4].strip()
    return seq_vert, seq_horiz, GAP, mismatch, match


In [119]:
def smith_waterman(matriz, seq_vert, seq_horiz, GAP, mismatch, match):
    GAP = int(GAP)
    mismatch = int(mismatch)
    match = int(match)

    num_lin = len(matriz)
    num_col = len(matriz[0])
_
    for i in range(num_lin):
        for j in range(num_col):
            if j == 0:
                matriz[i][j] = 5
            

IndentationError: unexpected indent (2697639420.py, line 9)

In [ ]:
def def_matriz(seq_vert, seq_horiz):

    num_col = len(seq_vert) + 1
    num_lin = len(seq_horiz) + 1
    matriz = np.zeros((num_col, num_lin))

    return matriz

In [ ]:
# teste de uso das variáveis
print("Vertical:", read_arq()[0])
print("Horizontal:", read_arq()[1])
print("GAP:", read_arq()[2])
print("Mismatch:", read_arq()[3])
print("Match:", read_arq()[4])

matriz = def_matriz(read_arq()[0], read_arq()[1])
smith_waterman(matriz, read_arq()[0], read_arq()[1], read_arq()[2], read_arq()[3], read_arq()[4])


Vertical: CCCUCAUCGCAUCUCCGCUC
Horizontal: CCCCGCCGCGCCC
GAP: -2
Mismatch: -1
Match: 3
[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0.