In [184]:
import numpy as np
import re 

In [185]:

def read_arq():
    with open('input.txt', 'r') as arquivo:
        linhas = arquivo.readlines()
    seq_vert = linhas[0].strip()
    seq_horiz = linhas[1].strip()
    GAP = linhas[2].strip()
    mismatch = linhas[3].strip()
    match = linhas[4].strip()
    return seq_vert, seq_horiz, GAP, mismatch, match


In [186]:
def smith_waterman(matriz, seq_vert, seq_horiz, GAP, mismatch, match):
    GAP = int(GAP)
    mismatch = int(mismatch)
    match = int(match)

    num_lin = len(matriz)
    num_col = len(matriz[0])

    sum = 0

    #set GAP first line
    for i in range(num_lin):
        for j in range(num_col):
            if j == 0 and i != 0:
                sum = sum + GAP
                matriz[i][j] = sum

    sum = 0
    
    #set GAP first column
    for i in range(num_lin):
        for j in range(num_col):
            if i == 0 and j != 0:
                sum = sum + 5
                matriz[i][j] = sum


    # for i in range(1, num_lin):
    #     for j in range(1, num_col):
    #         matriz[i][j] = -27

    
    for i in range(1, num_lin):
        for j in range(1, num_col):
                max_value = max(matriz[i-1][j-1], matriz[i-1][j], matriz[i][j-1])
                matriz[i][j] = max_value


    return matriz
            

In [187]:
def def_matriz(seq_vert, seq_horiz):

    num_col = len(seq_vert) + 1
    num_lin = len(seq_horiz) + 1
    matriz = np.zeros((num_col, num_lin))

    return matriz

In [188]:
# teste de uso das variáveis
print("Vertical:", read_arq()[0])
print("Horizontal:", read_arq()[1])
print("GAP:", read_arq()[2])
print("Mismatch:", read_arq()[3])
print("Match:", read_arq()[4])

matriz = def_matriz(read_arq()[0], read_arq()[1])
matriz = smith_waterman(matriz, read_arq()[0], read_arq()[1], read_arq()[2], read_arq()[3], read_arq()[4])

print(matriz)


Vertical: ATCG
Horizontal: TCG
GAP: -2
Mismatch: -1
Match: 1
[[ 0.  5. 10. 15.]
 [-2.  5. 10. 15.]
 [-4.  5. 10. 15.]
 [-6.  5. 10. 15.]
 [-8.  5. 10. 15.]]
